import Head from "next/head";
import { useRouter } from "next/router";
import { Routes } from "@/constants";
import Link from "next/link";

const navLinks = [
  {
    href: Routes.HOME,
    label: "Home",
  },
  {
    href: Routes.ABOUT,
    label: "About",
  },
  {
    href: Routes.BLOG,
    label: "Blog",
  },
];

export default function App({ Component, pageProps }) {
  const router = useRouter();
  const parsedRoute = `/${router.route.split("/")[1]}`;

  return (
    <>
      <Head>
        <title>Merge Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {navLinks.map((link) => {
            return (
              <Link
                style={{color: link.href === parsedRoute ? 'hotpink' : 'blue'}}
                key={link.href}
                href={link.href}
              >
                {link.label}
              </Link>
            );
          })}
        </div>
      </div>
      <Component {...pageProps} />
    </>
  );
}
