import Head from 'next/head';
import { Navbar, NextUIProvider, Link } from '@nextui-org/react';
import { useRouter } from 'next/router';
import { Routes } from '@/constants';

const navLinks = [
  {
    href: Routes.HOME,
    label: 'Home',
  },
  {
    href: Routes.ABOUT,
    label: 'About',
  },
  {
    href: Routes.BLOG,
    label: 'Blog',
  },
];

export default function App({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Merge Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextUIProvider>
        <Navbar isBordered variant="floating">
          <Navbar.Toggle showIn="xs" />
          <Navbar.Content
            css={{ jc: 'center', w: '100%' }}
            hideIn="xs"
            variant="highlight-rounded">
            {navLinks.map((link) => {
              return (
                <Navbar.Link
                  isActive={link.href === router.route}
                  key={link.href}
                  href={link.href}>
                  {link.label}
                </Navbar.Link>
              );
            })}
          </Navbar.Content>
          <Navbar.Collapse disableAnimation>
            {navLinks.map((item) => {
              const isActive = item.href === router.route;
              return (
                <Navbar.CollapseItem
                  key={item.href}
                  activeColor="warning"
                  css={{
                    color: isActive ? '$error' : '',
                  }}
                  isActive={isActive}>
                  <Link
                    color="inherit"
                    css={{
                      minWidth: '100%',
                    }}
                    href={item.href}>
                    {item.label}
                  </Link>
                </Navbar.CollapseItem>
              );
            })}
          </Navbar.Collapse>
        </Navbar>
        <Component {...pageProps} />
      </NextUIProvider>
    </>
  );
}
